version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./converted:/app/converted
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
